// Code generated by protoc-gen-go. DO NOT EDIT.
// source: nim.proto

package nim

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameParameter struct {
	NumberOfColumns      uint32   `protobuf:"varint,1,opt,name=number_of_columns,json=numberOfColumns,proto3" json:"number_of_columns,omitempty"`
	NumberOfStones       uint32   `protobuf:"varint,2,opt,name=number_of_stones,json=numberOfStones,proto3" json:"number_of_stones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameParameter) Reset()         { *m = GameParameter{} }
func (m *GameParameter) String() string { return proto.CompactTextString(m) }
func (*GameParameter) ProtoMessage()    {}
func (*GameParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_2087ae8459008b12, []int{0}
}

func (m *GameParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameParameter.Unmarshal(m, b)
}
func (m *GameParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameParameter.Marshal(b, m, deterministic)
}
func (m *GameParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameParameter.Merge(m, src)
}
func (m *GameParameter) XXX_Size() int {
	return xxx_messageInfo_GameParameter.Size(m)
}
func (m *GameParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GameParameter.DiscardUnknown(m)
}

var xxx_messageInfo_GameParameter proto.InternalMessageInfo

func (m *GameParameter) GetNumberOfColumns() uint32 {
	if m != nil {
		return m.NumberOfColumns
	}
	return 0
}

func (m *GameParameter) GetNumberOfStones() uint32 {
	if m != nil {
		return m.NumberOfStones
	}
	return 0
}

type GameTurn struct {
	TargetColumn         uint32   `protobuf:"varint,1,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	NumberToTake         uint32   `protobuf:"varint,2,opt,name=number_to_take,json=numberToTake,proto3" json:"number_to_take,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameTurn) Reset()         { *m = GameTurn{} }
func (m *GameTurn) String() string { return proto.CompactTextString(m) }
func (*GameTurn) ProtoMessage()    {}
func (*GameTurn) Descriptor() ([]byte, []int) {
	return fileDescriptor_2087ae8459008b12, []int{1}
}

func (m *GameTurn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTurn.Unmarshal(m, b)
}
func (m *GameTurn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTurn.Marshal(b, m, deterministic)
}
func (m *GameTurn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTurn.Merge(m, src)
}
func (m *GameTurn) XXX_Size() int {
	return xxx_messageInfo_GameTurn.Size(m)
}
func (m *GameTurn) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTurn.DiscardUnknown(m)
}

var xxx_messageInfo_GameTurn proto.InternalMessageInfo

func (m *GameTurn) GetTargetColumn() uint32 {
	if m != nil {
		return m.TargetColumn
	}
	return 0
}

func (m *GameTurn) GetNumberToTake() uint32 {
	if m != nil {
		return m.NumberToTake
	}
	return 0
}

type GameState struct {
	Columns              string   `protobuf:"bytes,1,opt,name=columns,proto3" json:"columns,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_2087ae8459008b12, []int{2}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetColumns() string {
	if m != nil {
		return m.Columns
	}
	return ""
}

func init() {
	proto.RegisterType((*GameParameter)(nil), "nim.GameParameter")
	proto.RegisterType((*GameTurn)(nil), "nim.GameTurn")
	proto.RegisterType((*GameState)(nil), "nim.GameState")
}

func init() {
	proto.RegisterFile("nim.proto", fileDescriptor_2087ae8459008b12)
}

var fileDescriptor_2087ae8459008b12 = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xb1, 0x4a, 0xc4, 0x40,
	0x10, 0x40, 0x39, 0x05, 0x35, 0xc3, 0x45, 0xbd, 0xb5, 0x49, 0x29, 0x51, 0xe1, 0xb0, 0xf0, 0x0a,
	0xff, 0x40, 0x0b, 0x4b, 0xe5, 0x12, 0x1b, 0x9b, 0x65, 0x22, 0x93, 0x10, 0xd6, 0xd9, 0x09, 0x9b,
	0xc9, 0xff, 0x4b, 0xb2, 0x1b, 0xb4, 0xdc, 0xb7, 0x8f, 0x37, 0xc3, 0x40, 0xe6, 0x7b, 0x7e, 0x1a,
	0x82, 0xa8, 0x98, 0x53, 0xdf, 0x73, 0x49, 0x90, 0xbf, 0x21, 0xd3, 0x07, 0x06, 0x64, 0x52, 0x0a,
	0xe6, 0x11, 0x76, 0x7e, 0xe2, 0x86, 0x82, 0x95, 0xd6, 0x7e, 0xcb, 0xcf, 0xc4, 0x7e, 0x2c, 0x36,
	0xb7, 0x9b, 0x7d, 0x7e, 0xbc, 0x8a, 0x1f, 0xef, 0xed, 0x6b, 0xc4, 0x66, 0x0f, 0xd7, 0x7f, 0xee,
	0xa8, 0xe2, 0x69, 0x2c, 0x4e, 0x16, 0xf5, 0x72, 0x55, 0xab, 0x85, 0x96, 0x9f, 0x70, 0x31, 0x8f,
	0xa9, 0xa7, 0xe0, 0xcd, 0x1d, 0xe4, 0x8a, 0xa1, 0x23, 0x4d, 0xf9, 0x54, 0xdf, 0x46, 0x18, 0xdb,
	0xe6, 0x1e, 0x52, 0xc2, 0xaa, 0x58, 0x45, 0x47, 0x29, 0xbc, 0x8d, 0xb4, 0x96, 0x1a, 0x1d, 0x95,
	0x0f, 0x90, 0xcd, 0xd9, 0x4a, 0x51, 0xc9, 0x14, 0x70, 0xfe, 0x7f, 0xdf, 0xec, 0xb8, 0x3e, 0x5f,
	0x6e, 0xbe, 0x76, 0x4a, 0x4e, 0x6c, 0x87, 0x4c, 0x87, 0xc1, 0x75, 0x07, 0xdf, 0x73, 0x73, 0xb6,
	0x5c, 0xe1, 0xf9, 0x37, 0x00, 0x00, 0xff, 0xff, 0x00, 0x83, 0xbb, 0x80, 0x12, 0x01, 0x00, 0x00,
}
