// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dots-and-boxes.proto

package dab

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GameParameter struct {
	NumberOfVerticalColumns   uint32   `protobuf:"varint,1,opt,name=number_of_vertical_columns,json=numberOfVerticalColumns,proto3" json:"number_of_vertical_columns,omitempty"`
	NumberOfHorizontalColumns uint32   `protobuf:"varint,2,opt,name=number_of_horizontal_columns,json=numberOfHorizontalColumns,proto3" json:"number_of_horizontal_columns,omitempty"`
	XXX_NoUnkeyedLiteral      struct{} `json:"-"`
	XXX_unrecognized          []byte   `json:"-"`
	XXX_sizecache             int32    `json:"-"`
}

func (m *GameParameter) Reset()         { *m = GameParameter{} }
func (m *GameParameter) String() string { return proto.CompactTextString(m) }
func (*GameParameter) ProtoMessage()    {}
func (*GameParameter) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e360a3be067847, []int{0}
}

func (m *GameParameter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameParameter.Unmarshal(m, b)
}
func (m *GameParameter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameParameter.Marshal(b, m, deterministic)
}
func (m *GameParameter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameParameter.Merge(m, src)
}
func (m *GameParameter) XXX_Size() int {
	return xxx_messageInfo_GameParameter.Size(m)
}
func (m *GameParameter) XXX_DiscardUnknown() {
	xxx_messageInfo_GameParameter.DiscardUnknown(m)
}

var xxx_messageInfo_GameParameter proto.InternalMessageInfo

func (m *GameParameter) GetNumberOfVerticalColumns() uint32 {
	if m != nil {
		return m.NumberOfVerticalColumns
	}
	return 0
}

func (m *GameParameter) GetNumberOfHorizontalColumns() uint32 {
	if m != nil {
		return m.NumberOfHorizontalColumns
	}
	return 0
}

type GameTurn struct {
	Vertical             bool     `protobuf:"varint,1,opt,name=vertical,proto3" json:"vertical,omitempty"`
	TargetColumn         uint32   `protobuf:"varint,2,opt,name=target_column,json=targetColumn,proto3" json:"target_column,omitempty"`
	TargetGap            uint32   `protobuf:"varint,3,opt,name=target_gap,json=targetGap,proto3" json:"target_gap,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameTurn) Reset()         { *m = GameTurn{} }
func (m *GameTurn) String() string { return proto.CompactTextString(m) }
func (*GameTurn) ProtoMessage()    {}
func (*GameTurn) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e360a3be067847, []int{1}
}

func (m *GameTurn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameTurn.Unmarshal(m, b)
}
func (m *GameTurn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameTurn.Marshal(b, m, deterministic)
}
func (m *GameTurn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameTurn.Merge(m, src)
}
func (m *GameTurn) XXX_Size() int {
	return xxx_messageInfo_GameTurn.Size(m)
}
func (m *GameTurn) XXX_DiscardUnknown() {
	xxx_messageInfo_GameTurn.DiscardUnknown(m)
}

var xxx_messageInfo_GameTurn proto.InternalMessageInfo

func (m *GameTurn) GetVertical() bool {
	if m != nil {
		return m.Vertical
	}
	return false
}

func (m *GameTurn) GetTargetColumn() uint32 {
	if m != nil {
		return m.TargetColumn
	}
	return 0
}

func (m *GameTurn) GetTargetGap() uint32 {
	if m != nil {
		return m.TargetGap
	}
	return 0
}

type GameState struct {
	VerticalColumns      uint32   `protobuf:"varint,1,opt,name=vertical_columns,json=verticalColumns,proto3" json:"vertical_columns,omitempty"`
	HorizontalColumns    uint32   `protobuf:"varint,2,opt,name=horizontal_columns,json=horizontalColumns,proto3" json:"horizontal_columns,omitempty"`
	VerticalLines        []byte   `protobuf:"bytes,3,opt,name=vertical_lines,json=verticalLines,proto3" json:"vertical_lines,omitempty"`
	HorizontalLines      []byte   `protobuf:"bytes,4,opt,name=horizontal_lines,json=horizontalLines,proto3" json:"horizontal_lines,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameState) Reset()         { *m = GameState{} }
func (m *GameState) String() string { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()    {}
func (*GameState) Descriptor() ([]byte, []int) {
	return fileDescriptor_66e360a3be067847, []int{2}
}

func (m *GameState) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameState.Unmarshal(m, b)
}
func (m *GameState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameState.Marshal(b, m, deterministic)
}
func (m *GameState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameState.Merge(m, src)
}
func (m *GameState) XXX_Size() int {
	return xxx_messageInfo_GameState.Size(m)
}
func (m *GameState) XXX_DiscardUnknown() {
	xxx_messageInfo_GameState.DiscardUnknown(m)
}

var xxx_messageInfo_GameState proto.InternalMessageInfo

func (m *GameState) GetVerticalColumns() uint32 {
	if m != nil {
		return m.VerticalColumns
	}
	return 0
}

func (m *GameState) GetHorizontalColumns() uint32 {
	if m != nil {
		return m.HorizontalColumns
	}
	return 0
}

func (m *GameState) GetVerticalLines() []byte {
	if m != nil {
		return m.VerticalLines
	}
	return nil
}

func (m *GameState) GetHorizontalLines() []byte {
	if m != nil {
		return m.HorizontalLines
	}
	return nil
}

func init() {
	proto.RegisterType((*GameParameter)(nil), "dab.GameParameter")
	proto.RegisterType((*GameTurn)(nil), "dab.GameTurn")
	proto.RegisterType((*GameState)(nil), "dab.GameState")
}

func init() {
	proto.RegisterFile("dots-and-boxes.proto", fileDescriptor_66e360a3be067847)
}

var fileDescriptor_66e360a3be067847 = []byte{
	// 295 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x89, 0x15, 0x49, 0x87, 0xc6, 0xda, 0x55, 0xb0, 0x16, 0x05, 0x89, 0x08, 0x7a, 0x88,
	0x3d, 0x78, 0xf4, 0x20, 0xe8, 0xa1, 0x1e, 0x04, 0x25, 0x8a, 0x07, 0x2f, 0x61, 0xd2, 0x4c, 0xd3,
	0xd8, 0x64, 0x37, 0x6c, 0x36, 0x45, 0xfc, 0x0f, 0xfe, 0x1e, 0xff, 0x9e, 0x64, 0x37, 0x49, 0x4b,
	0xa1, 0xc7, 0x7d, 0xf3, 0xbd, 0x37, 0xf3, 0x58, 0x38, 0x8a, 0x84, 0x2a, 0x3c, 0xe4, 0x91, 0x17,
	0x8a, 0x6f, 0x2a, 0x6e, 0x72, 0x29, 0x94, 0x60, 0x9d, 0x08, 0x43, 0xf7, 0xd7, 0x02, 0x67, 0x82,
	0x19, 0xbd, 0xa2, 0xc4, 0x8c, 0x14, 0x49, 0x76, 0x07, 0x23, 0x5e, 0x66, 0x21, 0xc9, 0x40, 0xcc,
	0x82, 0x25, 0x49, 0x95, 0x4c, 0x31, 0x0d, 0xa6, 0x22, 0x2d, 0x33, 0x5e, 0x0c, 0xad, 0x73, 0xeb,
	0xca, 0xf1, 0x8f, 0x0d, 0xf1, 0x32, 0xfb, 0xa8, 0xe7, 0x8f, 0x66, 0xcc, 0xee, 0xe1, 0x74, 0x65,
	0x9e, 0x0b, 0x99, 0xfc, 0x08, 0xae, 0xd6, 0xec, 0x3b, 0xda, 0x7e, 0xd2, 0xd8, 0x9f, 0x5a, 0xa2,
	0x0e, 0x70, 0xbf, 0xc0, 0xae, 0xce, 0x79, 0x2f, 0x25, 0x67, 0x23, 0xb0, 0x9b, 0xfd, 0x7a, 0xaf,
	0xed, 0xb7, 0x6f, 0x76, 0x01, 0x8e, 0x42, 0x19, 0x93, 0xaa, 0xa3, 0xeb, 0xe4, 0x9e, 0x11, 0x4d,
	0x1a, 0x3b, 0x03, 0xa8, 0xa1, 0x18, 0xf3, 0x61, 0x47, 0x13, 0x5d, 0xa3, 0x4c, 0x30, 0x77, 0xff,
	0x2c, 0xe8, 0x56, 0xcb, 0xde, 0x14, 0x2a, 0x62, 0xd7, 0x70, 0xb0, 0xa5, 0x6d, 0x7f, 0xb9, 0xd1,
	0xd2, 0x03, 0xb6, 0xb5, 0xdb, 0x60, 0xbe, 0xd9, 0x89, 0x5d, 0xc2, 0x7e, 0x9b, 0x9c, 0x26, 0x9c,
	0x0a, 0x7d, 0x4a, 0xcf, 0x77, 0x1a, 0xf5, 0xb9, 0x12, 0xab, 0x03, 0xd6, 0x52, 0x0d, 0xb8, 0xab,
	0xc1, 0xfe, 0x4a, 0xd7, 0xe8, 0xc3, 0xe1, 0xe7, 0x40, 0xd1, 0x42, 0x04, 0x31, 0x66, 0x34, 0xce,
	0x17, 0xf1, 0x38, 0xc2, 0x30, 0xdc, 0xd3, 0xdf, 0x7a, 0xfb, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x65,
	0x1f, 0x0c, 0xfc, 0xee, 0x01, 0x00, 0x00,
}
